FEATURES = {
    "dashboard": ("📱 Menu UBot", "Menu utama UBot"),
    "ban": ("🚫 Ban", "Ban member"),
    "unban": ("♻️ Unban", "Unban member"),
    "mute": ("🔇 Mute", "Mute member"),
    "unmute": ("🔊 Unmute", "Unmute member"),
    "autoreply": ("🤖 Auto Reply", "Auto reply keyword"),
    "antispam": ("🛡️ Anti Spam", "Proteksi spam"),
    "translate": ("🌐 Translate", "Terjemahan"),
    "ai": ("🧠 AI Assistant", "Tanya AI"),
    "ocr": ("👁️ OCR", "Baca teks dari gambar"),
    "music": ("🎵 Song Search", "Cari lagu"),
    "movie": ("🎬 Movie Search", "Cari film"),
    "game": ("🎮 Game", "Game"),
    "quiz": ("🧩 Quiz", "Quiz"),
    "random": ("🎲 Random", "Random picker"),
    "textgen": ("✍️ Text Generator", "Generator teks"),
    "texttools": ("🔤 Text Tools", "Tools teks"),
    "jashare": ("📢 JaShare", "Share/campaign manager"),
    "payment": ("💳 Payment", "Tampilkan payment"),
    "qr": ("🔳 QR Generator", "Buat QR"),
}

COMMAND_FEATURES = {
    "menu": "dashboard",
    "pay": "payment",
    "ban": "ban",
    "unban": "unban",
    "mute": "mute",
    "unmute": "unmute",
    "autoreply": "autoreply",
    "delreply": "autoreply",
    "listreply": "autoreply",
    "antispam": "antispam",
    "translate": "translate",
    "ai": "ai",
    "ocr": "ocr",
    "song": "music",
    "music": "music",
    "movie": "movie",
    "game": "game",
    "quiz": "quiz",
    "random": "random",
    "textgen": "textgen",
    "texttools": "texttools",
    "jashare": "jashare",
    "qr": "qr",
}
CATEGORIES = {
    "👥 Group Management": ["ban","unban","mute","unmute","antispam"],
    "🤖 Automation": ["autoreply","jashare"],
    "🧠 AI & Tools": ["ai","translate","ocr","textgen","texttools","qr"],
    "🎵 Media": ["music","movie"],
    "🎮 Games": ["game","quiz","random"],
    "💳 Payment": ["payment"],
}
